### ISSUE TITLE
Module 'angularSpinner' is not available!

### ISSUE THREAD

**Issue by johhansantana** [rpocklin/angular-ui-view-spinner#3]
I've installed angular ui view spinner with bower as the readme file stated, but I keep getting this error after I add it:

> angular.module('myapp', ['angularSpinner', 'ui.router', 'angular-ui-view-spinner'])
>   .config(['$stateProvider', '$urlRouterProvider', function ($stateProvider, $urlRouterProvider, $scope) {
>     $urlRouterProvider.otherwise('/');

I brings the error. What am I doing wrong here?

I'm using AngularJS v1.4.7

**Comment by rpocklin** [comment]
Have you included the file which defines the angularSpinner module?  That's probably why.

**Comment by johhansantana** [comment]
oh, I'm so sorry, I didn't, that fixed. Thank you.

**Comment by rpocklin** [comment]
I noticed bower.json didn't define the main / src files, which it should have - if you were using an auto-includer (ie. gulp/grunt -> index.html) that's probably why it failed.  I've commited this and re-tagged v1.0.0
